### ISSUE TITLE
Speed up pipeline with multiple threads

### ISSUE THREAD

**Issue by eebrown** [tkkarjal/magia#22]
Thanks very much for open-sourcing your pipeline. I have got it to run on my system by changing the hardcoded paths in the scripts, and hope to compare the results to my current pipeline.

I thought I would suggest that you may be able to increase the processing speed of the pipeline by adding `-parallel ` to the recon-all command. This defaults to allowing 4 cores for OpenMP, and cores can be further specified by using `-parallel -openmp n` where n is the number of cores (see https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes). It helped a lot on my system.

**Comment by tkkarjal** [comment]
I am very glad to hear you have found magia useful! Just for curiosity, how long did it take for you to set it up on your system? Also, where are you reading the metadata from? I am aware of the parallel computing possibility in FreeSurfer, but I have decided not to use it because we have a habit of running several subjects at once. Having e.g. 10 magia processes running simultaneously, and each of them then opening up 4 cores each... It is easy to see users running into troubles with that.

**Comment by eebrown** [comment]
It took a few hours to make a few changes to get it to work locally. I already had the dependencies installed. I needed to change all of the paths in the scripts that were hard-coded to my own local directories (I did this via getenv/setenv for portability). To specify the model and meta-data, I just entered it into Matlab as structs, then ran run_magia('subj1', metadata, model). It seems to have worked for tests with PIB. I think if you plan to make this more accessible it would make sense to change the hard-coded paths to environment variables, and list them all in the wiki. If you would like I could try a pull request so you can see the changes.

**Comment by tkkarjal** [comment]
Ok, that's awesome. Changing the hard-coded paths is definitely something that should be done, so if you could create a pull request I am sure that would speed things up. Thanks!

**Comment by tkkarjal** [comment]
Closed because the parallel option could cause instabilities if used carelessly.
